# Generated by Django 4.1.1 on 2022-11-20 13:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trailer",
                    models.CharField(
                        choices=[
                            ("Refrigerator", "Refrigerator"),
                            ("Curtain Trailer", "Curtain Trailer"),
                            ("Mega Trailer", "Mega Trailer"),
                            ("Box Trailer", "Box Trailer"),
                            ("Container Trailer", "Container Trailer"),
                            ("Tanker", "Tanker"),
                        ],
                        default="Curtain Trailer",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trailer Type",
                "verbose_name_plural": "Trailer Types",
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("contact_person", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=255, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("vehicle_name", models.CharField(max_length=50, null=True)),
                (
                    "truck_registration",
                    django_countries.fields.CountryField(max_length=2),
                ),
                ("truck_plates", models.CharField(max_length=50, null=True)),
                (
                    "trailer_registration",
                    django_countries.fields.CountryField(max_length=2),
                ),
                ("trailer_plates", models.CharField(max_length=50, null=True)),
                (
                    "position_country",
                    django_countries.fields.CountryField(max_length=2),
                ),
                ("position_postcode", models.CharField(max_length=25, null=True)),
                ("position_city", models.CharField(max_length=100, null=True)),
                (
                    "truck_status",
                    models.CharField(
                        choices=[
                            ("Actual", "Actual"),
                            ("Booked", "Booked"),
                            ("Transit", "Transit"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Actual",
                        max_length=15,
                    ),
                ),
                (
                    "truck_trailer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="truck_trailer",
                        to="carrier.trailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Truck",
                "verbose_name_plural": "Trucks",
            },
        ),
    ]
