# Generated by Django 4.1.1 on 2022-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("Refrigerator", "Refrigerator"),
                            ("Curtain Trailer", "Curtain Trailer"),
                            ("Mega Trailer", "Mega Trailer"),
                            ("Box Trailer", "Box Trailer"),
                            ("Container Trailer", "Container Trailer"),
                            ("Tanker", "Tanker"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
            },
        ),
    ]
